;================================================================================
;Universidad del Valle de Guatemala
;Programacion de microcontroladores
;Proyecto1.asm
;Josué Castro - 22082
;Creado 21/02/2025
;Modificado 16/03/2025
;================================================================================
;Encabezado
;================================================================================
.include "M328PDEF.INC"
.cseg 
.def ESTADO = R20
.org 0x00
	JMP		MAIN

.org 0x0006
	JMP		ISR_PCINT0

.org 0x0012
	JMP		ISR_TIMER2

.org 0x0020
	JMP		ISR_TIMER0

;================================================================================
;TABLA
;;================================================================================

TABLA7SEG: .db	 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90

MAIN:
;================================================================================
;Stack
;================================================================================
	LDI		R16, LOW(RAMEND)
	OUT		SPL, R16 
	LDI		R17, HIGH(RAMEND)
	OUT		SPL, R17

;================================================================================
;Configuracion
;================================================================================
SETUP:
	//OSCILADOR
	LDI		R16, (1 << CLKPCE)	;HABILITA EL PRESCALER
	STS		CLKPR, R16 
	LDI		R16, 6				;OSCILADOR DE 250kHz
	STS		CLKPR, R16
	
	//SALIDAS Y ENTRADAS
	LDI		R16, 0b0000_0000	;
	STS		UCSR0B, R16			;DESABILITO TX Y RX

	LDI		R16, 0b0000_0111	;
	OUT		PORTB, R16			;COLOCO EL PUERTO B COMO PULL-UP
	LDI		R16, 0b1111_1000	;
	OUT		DDRB, R16			;COLOCO EL PUERTO B COMO ENTRADA
	LDI		R16, 0b1111_1111	;

	OUT		DDRC, R16			;COLOCO EL PUERTO C COMO SALIDA
	LDI		R16, 0b1111_1111	;

	OUT		DDRD, R16			;COLOCO EL PUERTO D COMO SALIDA

	//INTERRUPCIONES
	LDI		R16, 7
	STS		PCMSK0, R16			;HABILITA PCINT0 y PCINT1
	LDI		R16, 1				;
	STS		PCICR, R16			;HABILITA PCIE0

; Configuración Timer 0 
	
	LDI R16, 0
	OUT TCCR0A, R16 
	LDI R16, 4 //256 timer prescaler
	OUT TCCR0B, R16
	LDI R16, 1
	STS TIMSK0, R16
	LDI R16, 100
	OUT TCNT0, R16

; Configuración del Timer2
	LDI  R16, 0              ; CONTADOR NORMAL
	STS  TCCR2A, R16         ; Configura TCCR2A
	
	LDI  R16, 7             ; Prescaler de 1024 (Modo normal)
	;LDI R16, 1				 ; Sin Prescaler (MODO RAPIDO)	
		
	STS  TCCR2B, R16         ; Configura TCCR2B
	LDI  R16, 1              ; Habilita la interrupción por desbordamiento
	STS  TIMSK2, R16         ; Configura TIMSK2
	LDI  R16, 11             ; Valor inicial del contador
	STS  TCNT2, R16          ; Carga el valor inicial en TCNT2

	//REGISTROS
	LDI		R16, 0				;AUXILIAR O TEMPORAL
	LDI		R17, 0				;BANDERA INCREMENTAR O DECREMENTAR

	LDI		R18, 0				;UNIDADES MINUTOS
	LDI		R19, 0				;DECENAS MINUTOS
	LDI		R28, 0				;UNIDADES HORAS
	LDI		R29, 0				;DECENAS HORAS

	LDI		R20, 0				;CONTADOR DE ESTADOS
	LDI		R21, 0				;CONTADOR DE SEGUNGOS
	LDI		R22, 0				;CAMBIO DE PARPADEO DE DISPLAY
	
	LDI		R23, 0				;CONTADOR UNIDADES HORA
	LDI		R24, 0				;CONTADOR DECENAS HORA
	LDI		R25, 0				;CONTADOR DE DECENAS - HORAS
	LDI		R26, 0				;CONTADOR DE DECENAS - HORAS

	LDI		R27, 0				;

	LDI		R30, 0				;
	LDI		R31, 0				;

	LDI		R30, 1
	MOV		R9, R30
	
	CLR		R15					;
	CLR		ESTADO				;INCIALIZAMOS EL REGISTRO DE ESTADO

	LDI		R30, 1
	MOV		R8, R30
	LDI		R30, 1
	MOV		R9, R30
	LDI		R30, 1
	MOV		R11, R30
	LDI		R30, 1
	MOV		R13, R30
	CLR		R12
	CLR		R10

	CLR		R2
	CLR		R3
	CLR		R4
	CLR		R5
	CLR		R6
	CLR		R7

	LPM		R18, Z				;VALORES INICIALES  DE LOS DISPLAYS
	OUT		PORTD, R18			
	LPM		R19, Z				;VALORES INICIALES  DE LOS DISPLAYS
	OUT		PORTD, R19			
	LPM		R28, Z				;VALORES INICIALES  DE LOS DISPLAYS
	OUT		PORTD, R28
	LPM		R29, Z				;VALORES INICIALES  DE LOS DISPLAYS
	OUT		PORTD, R29
	SEI

;***************************
;Bucle infinito
;***************************
LOOP:	
	CPI		ESTADO, 0
	BREQ	ESTADO0
	CPI		ESTADO, 1
	BREQ	ESTADO1
	CPI		ESTADO, 2
	BREQ	ESTADO2
	CPI		ESTADO, 3
	BREQ	ESTADO3
	CPI		ESTADO, 4
	BREQ	ESTADO4
	CPI		ESTADO, 5
	BREQ	ESTADO5
	RJMP	LOOP
;================================================================================
;ESTADOS
;================================================================================

;Hora
ESTADO0:
	CBI		PORTB, PB3		;
	CBI		PORTB, PB4
	SBI		PORTB, PB5		;Encender LED DE INDICACIÓN
	CALL	HORA
	RJMP	LOOP

;Configuración de hora

ESTADO1:
	CBI		PORTB, PB3
	CBI		PORTB, PB4
	CBI		PORTB, PB5
	CALL	CONFIG_HORA
	RJMP	LOOP

;Fecha

ESTADO2:
	CBI		PORTB, PB3
	SBI		PORTB, PB4	;Encender LED DE INDICACIÓN DE FECHA
	CBI		PORTB, PB5
	CALL	FECHA
	RJMP	LOOP

;Configuracion de fecha
ESTADO3:
	CBI		PORTB, PB3
	CBI		PORTB, PB4
	CBI		PORTB, PB5
	CALL	CONFIG_FECHA
	RJMP	LOOP
;Configuracion de alarma
ESTADO4:
	SBI		PORTB, PB3	;ENCENDER LED DE INDICACIÓN DE ALARMA 
	CBI		PORTB, PB4
	CBI		PORTB, PB5
	CALL	CONFIG_ALARMA
	RJMP	LOOP

; Activación de alarma
ESTADO5:
	CBI		PORTB, PB3
	CBI		PORTB, PB4
	SBI		PORTB, PB5
	CALL	ALARMA
	RJMP	LOOP


;================================================================================
;HORA
;================================================================================
HORA:
	CBI		PORTC, PC5
	CPI		R21, 60					; VERIFICASMO SI R21 = 60 PARA QUE HAGA 1MIN
	BRNE	NO21					; SALTAMOS AL ESTADO INICIAL
	LDI		R21,0					; SI SON IGUALES REINICIA R21
	INC		R23
NO21:
	CALL	CUENTA
	ADD		ZL, R23
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R24
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R25
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R26
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	RET

;================================================================================
							;CONFIGURACION-HORA
;================================================================================

CONFIG_HORA:	
	CALL	CUENTA
	ADD		ZL, R23
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R24
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R25
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R26
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	RET

;;================================================================================
;								FECHA
;=================================================================================

FECHA:
	CPI		R21, 60					; VERIFICASMO SI R21 = 60 PARA QUE HAGA 1MIN
	BRNE	NO22					; SALTAMOS AL ESTADO INICIAL
	LDI		R21,0					; SI SON IGUALES REINICIA R21
	INC		R23
NO22:
	CALL	CUENTA
	ADD		ZL, R11
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R10
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R13
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R12
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	RET	

;================================================================================
;							CONFIGURACION-FECHA
;================================================================================

CONFIG_FECHA:
	CALL	CUENTA
	ADD		ZL, R11
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R10
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R13
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)

	ADD		ZL, R12
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	RET

;;================================================================================
;							CONFIGURACION-ALARMA
;================================================================================
CONFIG_ALARMA:
	CALL	CUENTA_ALARMA
	ADD		ZL, R3
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R4
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R6
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R7
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	RET

;================================================================================
;									ALARMA
;================================================================================

ALARMA:
	MOV		R16, R3					
	CP		R23, R16				;VERIFICAMOS SI EL VALOR DEL DISPLAY 1 ES IGUAL AL DE LA CONFIG ALARMA
	BRNE	NO_1
	MOV		R16, R4
	CP		R24, R16				;VERIFICAMOS SI EL VALOR DEL DISPLAY 2 ES IGUAL AL DE LA CONFIG ALARMA
	BRNE	NO_1
	MOV		R16, R6
	CP		R25, R16				;VERIFICAMOS SI EL VALOR DEL DISPLAY 3 ES IGUAL AL DE LA CONFIG ALARMA
	BRNE	NO_1
	MOV		R16, R7
	CP		R26, R16				;VERIFICAMOS SI EL VALOR DEL DISPLAY 4 ES IGUAL AL DE LA CONFIG ALARMA
	BRNE	NO_1
	SBI		PORTC, PC5				;SI TODO LO ANTERIOR ES IGUAL, SE ACTIVA LA ALARMA
	RJMP	NO_2
NO_1:
	CBI		PORTC, PC5				;SI TODO LO ANTERIOR NO ES IGUAL, NO SE ACTIVA LA ALARMA
NO_2:
	CPI		R21, 60					; VERIFICASMO SI R21 = 60 PARA QUE HAGA 1MIN
	BRNE	NO23					; SALTAMOS AL ESTADO INICIAL
	LDI		R21,0					; SI SON IGUALES REINICIA R21
	INC		R23
NO23:
	CALL	CUENTA
	ADD		ZL, R23
	LPM		R18, Z					; CARGA A R18 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R24
	LPM		R19, Z					; CARGA A R19 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R25
	LPM		R28, Z					; CARGA A R28 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)
	ADD		ZL, R26
	LPM		R29, Z					; CARGA A R29 EL VALOR DE ESA POSICION
	LDI		ZL, LOW(TABLA7SEG << 1)
	LDI		ZH, HIGH(TABLA7SEG << 1)	
	RET

;**************************************************************
CUENTA:
	CPI		R23, 10					;VALOR MAXIMO PARA INCRIMENTAR LAS DECENAS DE LOS MINUTOS
	BRNE	SALIR_CUENTA
	CLR		R23
	INC		R24
	CPI		R24, 6					;VALOR MAXIMO PARA INCRIMENTAR LAS UNIDADES DE LAS HORAS
	BRNE	SALIR_CUENTA 
	CLR		R24

	INC		R15						
	MOV		R16, R15
	CPI		R16, 24					;;VALOR MAXIMO PARA INCRIMENTAR LOS DE LA FECHA
	BRNE	HORA_24
	CLR		R15
	CLR		R25
	CLR		R26

	RJMP	SALIR_CUENTA
HORA_24:
	INC		R25
	CPI		R25, 10					;VALOR MAXIMO PARA INCRIMENTAR LAS DECENAS DE LOS HORAS
	BRNE	SALIR_CUENTA			; SI NO SON IGUALES
	CLR		R25
	INC		R26

	CALL	MESES
SALIR_CUENTA:
	RET


;**************************************************************
CUENTA_ALARMA:
	MOV		R16, R3
	CPI		R16, 10
	BRNE	SALIR_CUENTA_A
	CLR		R3
	INC		R4
	MOV		R16, R4
	CPI		R16, 6
	BRNE	SALIR_CUENTA_A
	CLR		R4

	INC		R5
	MOV		R16, R5
	CPI		R16, 24
	BRNE	HORA_24_A
	CLR		R5
	CLR		R6
	CLR		R7

	RJMP	SALIR_CUENTA_A
HORA_24_A:
	INC		R6
	MOV		R16, R6
	CPI		R16, 10					; VERIFICA SI ES EL VALOR MAXIMO 
	BRNE	SALIR_CUENTA_A			; SI NO SON IGUALES
	CLR		R6
	INC		R7

SALIR_CUENTA_A:
	RET

;;================================================================================
;MESES
;================================================================================

MESES:
	MOV		R30, R9					
	CPI		R30, 1					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES2
	CALL	MES31
	RJMP	SALIR_MESES
MES2:
	MOV		R30, R9
	CPI		R30, 2					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES3
	CALL	MES28
	RJMP	SALIR_MESES
MES3:
	MOV		R30, R9
	CPI		R30, 3					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES4
	CALL	MES31
	RJMP	SALIR_MESES
MES4:
	MOV		R30, R9
	CPI		R30, 4					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES5
	CALL	MES30
	RJMP	SALIR_MESES
MES5:
	MOV		R30, R9
	CPI		R30, 5					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES6
	CALL	MES31
	RJMP	SALIR_MESES
MES6:
	MOV		R30, R9
	CPI		R30, 6					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES7
	CALL	MES30
	RJMP	SALIR_MESES
MES7:
	MOV		R30, R9
	CPI		R30, 7					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES8
	CALL	MES31
	RJMP	SALIR_MESES
MES8:
	MOV		R30, R9
	CPI		R30, 8					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES9
	CALL	MES31
	RJMP	SALIR_MESES
MES9:
	MOV		R30, R9
	CPI		R30, 9					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES10
	CALL	MES30
	RJMP	SALIR_MESES
MES10:
	MOV		R30, R9
	CPI		R30, 10					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES11
	CALL	MES31
	RJMP	SALIR_MESES
MES11:
	MOV		R30, R9
	CPI		R30, 11					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MES12
	CALL	MES30
	RJMP	SALIR_MESES
MES12:
	MOV		R30, R9
	CPI		R30, 12					;VERIFICO SI EL MES ES DE 31, 30 O 28 DIAS
	BRNE	MESS
	CALL	MES31
	RJMP	SALIR_MESES
MESS:
	CLR		R9						;SI LELGA DESPUES DEL MES 12 REINICIAMOS TODO
	CLR		R10
	CLR		R12
	LDI		R30, 1
	MOV		R11, R30
	LDI		R30, 1
	MOV		R13, R30
	LDI		R30, 1
	MOV		R9, R30
	LDI		R30, 1
	MOV		R8, R30
SALIR_MESES:
	RET

;********MES DE 30********
MES30:
	MOV		R30, R8
	CPI		R30, 30
	BRNE	M30

	INC		R9	
	INC		R11
	MOV		R30, R11
	CPI		R30, 10
	BRNE	S30
	LDI		R30, 0
	MOV		R11, R30
	INC		R10
S30:
	LDI		R30, 1
	MOV		R13, R30
	CLR		R12
	LDI		R30, 1
	MOV		R8, R30
	RJMP	SM30
M30:
	INC		R8
	INC		R13
	MOV		R30, R13
	CPI		R30, 10
	BRNE	SM30
	CLR		R13

	INC		R12
SM30:
	RET

;********MES DE 31********
MES31:
	MOV		R30, R8
	CPI		R30, 31
	BRNE	M31
	
	MOV		R30, R9
	CPI		R30, 12
	BRNE	S31
	CLR		R9
	CLR		R11
	CLR		R10
	CLR		R12
S31:
	INC		R9	
	INC		R11
	LDI		R30, 1
	MOV		R13, R30
	CLR		R12
	LDI		R30, 1
	MOV		R8, R30
	RJMP	SM31
M31:
	INC		R8
	INC		R13
	MOV		R30, R13
	CPI		R30, 10
	BRNE	SM31
	CLR		R13

	INC		R12
SM31:
	RET

;********MES DE 28********
MES28:
	MOV		R30, R8
	CPI		R30, 28
	BRNE	M28

	INC		R9	
	INC		R11
	LDI		R30, 1
	MOV		R13, R30
	CLR		R12
	LDI		R30, 1
	MOV		R8, R30
	RJMP	SM28
M28:
	INC		R8
	INC		R13
	MOV		R30, R13
	CPI		R30, 10
	BRNE	SM28
	CLR		R13

	INC		R12
SM28:
	RET


;************************
;Vector 1 - Pin Change
;************************
ISR_PCINT0:
	PUSH	R16					;SACAMOS DE LA PILA
	OUT		SREG, R16			;
	PUSH	R16	
	SBIS	PINB, PB0
	RJMP	MODO
	SBIS	PINB, PB1
	RJMP	BOTON2
	SBIS	PINB, PB2
	RJMP	BOTON3	
	RJMP	SALIR_PCINT0
MODO:	
	CPI		ESTADO, 5
	BREQ	ESTADO_INCIAL
	INC		ESTADO
	CLR		R21
	RJMP	SALIR_PCINT0

;***************BOTON-2**********************
BOTON2:
	CPI		ESTADO, 1
	BRNE	SB2
	INC		R23
	RJMP	SALIR_PCINT0
SB2:
	CPI		ESTADO, 3
	BRNE	SB22
	MOV		R16, R9
	CPI		R16, 12
	BRNE	SSSS
	CLR		R9
	CLR		R11
	CLR		R10
SSSS:
	INC		R9	
	INC		R11
	MOV		R16, R11
	CPI		R16, 10
	BRNE	SSS
	CLR		R11
	INC		R10
SSS:
	RJMP	SALIR_PCINT0
SB22:
	CPI		ESTADO, 4
	BRNE	SB222
	INC		R3
	RJMP	SALIR_PCINT0
SB222:
	RJMP	SALIR_PCINT0

;*************BOTON-3*************
BOTON3:
	CPI		ESTADO, 3
	BRNE	SB3
	CALL	MESES	; HAY QUE AGREGAR EL INCRMENTO DE HORAS (DEJARLO DE ULTIMO) PARA EL ESTADO 1
SB3:
	RJMP	SALIR_PCINT0

ESTADO_INCIAL:
	CLR		R21
	CLR		ESTADO

SALIR_PCINT0:
	POP		R16					;SACAMOS DE LA PILA
	OUT		SREG, R16			;
	POP		R16	
	RETI




;************************
;Vector 2 - Timer0 (10ms)
;************************
ISR_TIMER0:
	PUSH R16 ;GUARDAMOS EN LA PILA
	IN R16, SREG ;
	PUSH R16 ;
	INC R2
	MOV R16, R2
	CPI R16, 250
	BRNE PARPADEO ; SI YA PASARON 500MS SE ENCIANDE LOS DOS PUNTOS
	SBI PORTC, PC4
	CLR R2
	RJMP PARPADEO1 ; SI YA PASARON 500MS SE APAGAN LOS DOS PUNTOS

PARPADEO:
CBI PORTC, PC4

PARPADEO1:
	INC		R22
	CPI		R22, 1
	BRNE	DOS
	OUT		PORTD, R18			;MOSTRAMOS EN EL PUERO D EL VALOR DEL DISPLAY 1
	CBI		PORTC, PC1
	CBI		PORTC, PC2
	CBI		PORTC, PC3
	SBI		PORTC, PC0			;ACTIVAMOS SOLO EL DISPLAY 1
	
	RJMP	UNO	
DOS:
	CPI		R22, 2
	BRNE	TRES
	OUT		PORTD, R19			;MOSTRAMOS EN EL PUERO D EL VALOR DEL DISPLAY 2
	CBI		PORTC, PC0
	CBI		PORTC, PC2
	CBI		PORTC, PC3
	SBI		PORTC, PC1			;ACTIVAMOS SOLO EL DISPLAY 2
	
	RJMP	UNO	
TRES:
	CPI		R22, 3
	BRNE	CUATRO
	OUT		PORTD, R28			;MOSTRAMOS EN EL PUERO D EL VALOR DEL DISPLAY 3
	CBI		PORTC, PC0
	CBI		PORTC, PC1
	CBI		PORTC, PC3
	SBI		PORTC, PC2			;ACTIVAMOS SOLO EL DISPLAY 3
	
	RJMP	UNO
CUATRO:
	CPI		R22, 4
	BRNE	ZERO
	OUT		PORTD, R29			;MOSTRAMOS EN EL PUERO D EL VALOR DEL DISPLAY 4
	CBI		PORTC, PC0
	CBI		PORTC, PC1
	CBI		PORTC, PC2
	SBI		PORTC, PC3			;ACTIVAMOS SOLO EL DISPLAY 1
	LDI		R22, 0

	RJMP	UNO

ZERO:
	NOP
UNO: 
	LDI		R16, 254			;254 
	OUT		TCNT0, R16			;VALOR INICIAL 
	POP		R16					;SACAMOS DE LA PILA
	OUT		SREG, R16			;
	POP		R16					;
	RETI


;************************
;Vector 3 - Timer2 (1s)
;************************
ISR_TIMER2:
	PUSH	R16					;GUARDAMOS EN LA PILA
	IN		R16, SREG			;
	PUSH	R16					;
	
	INC		R21				 	;INCREMENTAMOS EL CONTADOR DE LOS 1S 

SALIR_T2:
	LDI		R16, 11				;11	
	STS		TCNT2, R16			;VALOR INICIAL
	POP		R16					;SACAMOS DE LA PILA
	OUT		SREG, R16			;
	POP		R16	
	RETI